spring:
  redis:
    database: 1
    host: 127.0.0.1
    password: 123456
  application:
    name: b-pan-server
  output:
    ansi:
      enabled: always
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:13306/b_pan?characterEncoding=utf8&serverTimeZone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans

swagger2:
  show: true
  group-name: ${spring.application.name}
  base-package: onem.baymax.pan
  title: b-pan-server docs
  description: b-pan-server docs
  terms-of-service-url: http://127.0.0.1:${server.port}
  contact-name: baymax
  contact-url: none
  contact-email: none
  version: 1.0

logging:
  file: ${user.home}/logs/${spring.application.name}/${spring.application.name}.log
  level:
    root: INFO